/**
 * `components/index.js` exists simply as a 'central export' for our components.
 * This way, we can import all of our components from the same place, rather than
 * having to figure out which file they belong to!
 */
export {default as Navbar} from './Navbar'
export {default as AddressForm} from './AddressForm'
export {default as AdminPageOrder} from './AdminPageOrder'
export {default as AdminPageUser} from './AdminPageUser'
export {Login, Signup} from './AuthForm'
export {default as CardSection} from './CardSection'
export {default as CartItem} from './CartItem'
export {default as Cart} from './Cart'
export {default as InjectedCheckoutForm} from './CheckoutForm'
export {default as CheckoutUserinfo} from './CheckoutUserInfo'
export {default as CheckoutOrderItem} from './CheckoutOrderItem'
export {default as CreateProduct} from './CreateProduct'
export {default as CreateProductForm} from './CreateProductForm'
export {default as EditProduct} from './EditProduct'
export {default as EditProductForm} from './EditProductForm'
export {default as Error} from './Error'
export {default as ItemDetails} from './ItemDetails'
export {default as OrderItem} from './OrderItem'
export {default as OrderSuccessPage} from './OrderSuccessPage'
export {default as OrderHistory} from './OrderHistory'
export {default as Pagination} from './Pagination'
export {default as PlaceOrder} from './PlaceOrder'
export {default as ProductDummy} from './ProductDummy'
export {default as SingleProduct} from './SingleProduct'
export {default as Tag} from './Tag'
export {default as TagProducts} from './TagProducts'
export {default as UserHome} from './UserHome'
export {default as UserProfile} from './UserProfile'
// export {default as AuthForm} from './AuthForm'

// export {default as CreateProduct} from './CreateProduct'
